server.port=8443
# Enforce HTTPS.
server.ssl.key-alias=sslserver
# Local lab keystore password.
server.ssl.key-store-password=changeit
# Use classpath keystore path for portability.
server.ssl.key-store=classpath:ssl-server.p12
server.ssl.key-store-type=PKCS12
